# Generated by Django 5.2.2 on 2025-06-09 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('puntuacion', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Puntuación de 1 a 5 estrellas')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-destacado', '-especial', 'nombre']},
        ),
        migrations.AddField(
            model_name='informacion',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='informacion',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='informacion',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='informacion',
            name='mision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='informacion',
            name='slogan',
            field=models.CharField(default='El Mejor Sabor de la Amazonía', max_length=300),
        ),
        migrations.AddField(
            model_name='informacion',
            name='vision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='informacion',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 9, 11, 24, 9, 703957, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='especial',
            field=models.BooleanField(default=False, help_text='Plato especial de la casa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
